<?php
$products = [
    "iphone" => [
        "name" => "iPhone",
        "price" => 45056,
        "weight" => 220,
        "discount" => 10,
        "picture_url" => "imgs/iphone.png",
    ],
    "ipad" => [
        "name" => "iPad",
        "price" => 60000,
        "weight" => 500,
        "discount" => 25,
        "picture_url" => "imgs/ipad.jpg",
    ],
    "vacuum-cleaner" => [
        "name" => "Dyson",
        "price" => 25000,
        "weight" => 3000,
        "discount" => 25,
        "picture_url" => "imgs/aspirateur.jpg",
    ],
    "brush" => [
        "name" => "Toothbrush",
        "price" => 300,
        "weight" => 10,
        "discount" => 10,
        "picture_url" => "imgs/brosse-a-dent.jpg",
    ],
    "glass" => [
        "name" => "Glass",
        "price" => 500,
        "weight" => 200,
        "discount" => 50,
        "picture_url" => "imgs/verre.jpg",
    ],
    "mouse" => [
        "name" => "Mouse",
        "price" => 5000,
        "weight" => 60,
        "discount" => null,
        "picture_url" => "imgs/souris.jpg",
    ],
    "mousee" => [
        "name" => "Mouse",
        "price" => 5000,
        "weight" => 60,
        "discount" => null,
        "picture_url" => "imgs/souris.jpg",
    ],
    "mouseee" => [
        "name" => "Mouse",
        "price" => 5000,
        "weight" => 60,
        "discount" => null,
        "picture_url" => "imgs/souris.jpg",
    ],
    "mouseeee" => [
        "name" => "Mouse",
        "price" => 5000,
        "weight" => 60,
        "discount" => null,
        "picture_url" => "imgs/souris.jpg",
    ],
    "mouseeeee" => [
        "name" => "Mouse",
        "price" => 5000,
        "weight" => 60,
        "discount" => null,
        "picture_url" => "imgs/souris.jpg",
    ],
    "mous" => [
        "name" => "Mouse",
        "price" => 5000,
        "weight" => 60,
        "discount" => null,
        "picture_url" => "imgs/souris.jpg",
    ]
];
